# This file is used to configure the models used in the touchdesigner project.
# Note: any cofig key ending with "dir" or "path" will be expanded to full paths.

ENABLE_SD: False

TE_LX_IP: 127.0.0.1
TE_LX_PORT: 3031

MSHIP_LX_IP: 10.0.0.2
MSHIP_LX_PORT: 3030

TE_PANG_IP: 10.0.0.3
TE_PANG_PORT: 4040

MSHIP_PANG_IP: 10.0.0.4
MSHIP_PANG_PORT: 4040