# This file is used to configure the models used in the touchdesigner project.
# Note: any cofig key ending with "dir" or "path" will be expanded to full paths.

TE_LX_IN_IP: "10.1.2.1" # lighting-2
TE_LX_IN_PORT: "7892"

STEMS_IN_IP: "10.1.2.1"  # lighting-2
STEMS_IN_PORT: "3032"

TE_ENGINE_IN_IP: "10.1.2.1"  # lighting-2
TE_ENGINE_IN_PORT: "6062"